#ifndef PHY_CHANNELS_H
#define PHY_CHANNELS_H

// Channel Definitions for the 868MHz SRD Band 
#define SRD_PHY_CHANNEL_BANDWIDTH_Hz 200000l
#define SRD_PHY_CHANNEL_SPACING_Hz   200000l
#define SRD_PHY_BAND_START_Hz     863000000l
#define SRD_PHY_BAND_END_Hz       869200000l
#define SRD_PHY_CHANNEL(ch) (SRD_PHY_BAND_START_Hz + (SRD_PHY_CHANNEL_BANDWIDTH_Hz / 2) + (ch * SRD_PHY_CHANNEL_SPACING_Hz))
#define SRD_MAX_CHANNEL (((SRD_PHY_BAND_END_Hz-SRD_PHY_BAND_START_Hz)/SRD_PHY_CHANNEL_SPACING_Hz)-1)

#endif // PHY_CHANNELS_H
